.travis.yml, Makefile, src/erl/clj_emitter.erl
=> [Closes #26] travis-ci integration

README.md
=> [Closes #26] travis-ci badge

LICENSE
=> [Closes #284] Add EPL v1.0 license same as Clojure

src/clj/clojure/core.clje, src/erl/clj_rt.erl, test/clj/examples/some_ns/one.clje, test/clj/examples/some_ns/three.clje, test/clj/examples/some_ns/two.clje, test/clj_compiler_SUITE.erl
=> [Fixes #287] Handle dashes correctly

README.md, src/clj/clojure/core.clje, src/clojerl.app.src, src/erl/clj_compiler.erl
=> [Closes #283] Basic documentation

src/clj/clojure/main.clje, src/clj/clojure/repl.clje, src/erl/clj_compiler.erl
=> [Closes #286] Full path for files

src/erl/clj_analyzer.erl, src/erl/clj_compiler.erl, src/erl/clj_env.erl, src/erl/clj_utils.erl
=> [Fixes #293] Missing location info

.gitattributes
=> [#297] Add .gitattributes with clje extension as Clojure

src/erl/clj_compiler.erl, src/erl/clj_emitter.erl, src/erl/clj_module.erl, src/erl/clj_utils.erl
=> [Closes #296] Replace "form(s)" for "module(s)"

elvis.config, src/erl/clj_compiler.erl, src/erl/clj_emitter.erl, src/erl/clj_emitter_pattern.erl, src/erl/clj_module.erl, src/erl/clj_utils.erl, src/erl/rbdict.erl, test/clj_compiler_SUITE.erl
=> [Fix #300] Fix elvis warnings

Makefile
=> [Fixes #302] Add correct path

include/clojerl.hrl, src/clj/clojure/core.clje, src/clj/clojure/main.clje, src/erl/clj_compiler.erl, src/erl/clj_module.erl, src/erl/clj_protocol.erl, src/erl/clj_reader.erl, src/erl/clj_utils.erl, test/clj/clojure/test_clojure/protocols.clje, test/clj_analyzer_SUITE.erl, test/clj_reader_SUITE.erl
=> [Fixes #289] REPL error beam not found

include/clojerl.hrl, src/erl/clj_emitter.erl, src/erl/clj_module.erl, test/clj/examples/on_load.clj
=> [Closes #304] Don't add on_load function when there are no expressions

Makefile, bin/compile, test/clj/benchmark/result.txt
=> [Closes #308] Process time and verbose options in compile script

src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl, test/clj/examples/pattern.clje, test/clj_analyzer_SUITE.erl
=> [Fixes #312] Introduce lexical renaming for underscore

src/erl/clj_utils.erl
=> [Closes #316] Compile with OTP 20.0-rc2

bootstrap/clojure.core.erl, elvis.config, src/clj/clojure/core.clje, src/erl/clj_analyzer.erl, src/erl/clj_compiler.erl, src/erl/clj_emitter.erl, src/erl/clj_reader.erl, src/erl/clojerl_sup.erl, src/erl/lang/clojerl.Namespace.erl, src/erl/lang/clojerl.String.erl, test/clj_compiler_SUITE.erl, test/clj_reader_SUITE.erl
=> [Closes #104 Closes #314] Create a type Namespace

src/clj/clojure/repl.clje, src/erl/erlang/erlang.io.StringWriter.erl, src/erl/lang/clojerl.Namespace.erl, test/erlang_io_StringWriter_SUITE.erl
=> [Closes #321] Implement clojure.repl/source

Makefile, src/clj/clojure/core_print.clje, src/clj/clojure/instant.clje, src/clj/clojure/string.clje, src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl, test/clj_analyzer_SUITE.erl
=> [Closes #323] Type hints ignored

.travis.yml, docs/differences-with-clojure.md
=> [Closes #163] Add document with differences from Clojure

src/clj/clojure/core.clje, src/erl/lang/collections/clojerl.Map.erl, src/erl/lang/collections/clojerl.TupleMap.erl, test/clojerl_Atom_SUITE.erl, test/clojerl_TupleMap_SUITE.erl
=> [Closes #327] Tuple maps

bootstrap/clojure.core.erl, src/clj/clojure/core_deftype.clje, src/clj/clojure/core_print.clje, src/erl/clj_rt.erl, src/erl/lang/clojerl.reader.TaggedLiteral.erl, src/erl/lang/collections/clojerl.Cons.erl, src/erl/lang/collections/clojerl.List.erl, src/erl/lang/collections/clojerl.Map.erl, src/erl/lang/collections/clojerl.Range.erl, src/erl/lang/collections/clojerl.Set.erl, src/erl/lang/collections/clojerl.SortedMap.erl, src/erl/lang/collections/clojerl.SortedSet.erl, src/erl/lang/collections/clojerl.TupleMap.erl, src/erl/lang/collections/clojerl.Vector.erl, src/erl/lang/collections/clojerl.erlang.List.erl, src/erl/lang/collections/clojerl.erlang.Map.erl, src/erl/lang/collections/clojerl.erlang.Tuple.erl, test/clj/clojure/test_clojure/reader.cljc, test/clojerl_LazySeq_SUITE.erl, test/clojerl_Map_SUITE.erl, test/clojerl_Range_SUITE.erl, test/clojerl_Reduced_SUITE.erl, test/clojerl_erlang_List_SUITE.erl, test/clojerl_erlang_Map_SUITE.erl, test/clojerl_erlang_Tuple_SUITE.erl, test/clojerl_reader_ReaderConditional_SUITE.erl, test/clojerl_reader_TaggedLiteral_SUITE.erl
=> [#335] Implement the same behaviour for str for collections as in Clojure

src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl
=> [Closes #337] Emit functions in defprotocol and don't include callback attributes

src/clj/clojure/core.clje, src/erl/lang/clojerl.MultiFn.erl, test/clj/clojure/test_clojure/multimethods.clje, test/clojerl_MultiFn_SUITE.erl
=> [Closes #339] Add multimethods.clje tests from original and fix bugs

src/erl/clj_analyzer.erl, src/erl/clj_reader.erl
=> [Closes #341] Metadata lost

src/erl/clj_module.erl
=> [Closes #343] Keep on_load expressions

src/clj/clojure/core.clje, src/erl/clj_emitter.erl
=> [Closes #345] Force evaluation order when emitting lists

src/erl/clj_reader.erl, test/clj_reader_SUITE.erl
=> [Closes #347] Use return_on in read_until to avoid complex checks

src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl
=> [#349] Dynamic vars that are functions should also check the current binding

src/clj/clojure/core.clje, src/erl/lang/clojerl.ExceptionInfo.erl, src/erl/lang/clojerl.Symbol.erl, src/erl/lang/protocols/clojerl.IError.erl, src/erl/lang/protocols/clojerl.IExceptionInfo.erl, test/clojerl_ExceptionInfo_SUITE.erl, test/clojerl_LazySeq_SUITE.erl
=> [Closes #352] Exception Info

Makefile, src/clj/clojure/core/server.clje, src/clj/clojure/stacktrace.clje, src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl, src/erl/erlang/erlang.io.PushbackReader.erl, test/clj/clojure/test_clojure/server.clje
=> [#237] Port clojure.core.server

src/erl/clj_utils.erl, test/clj/clojure/test_clojure/logic.clje, test/clj_reader_SUITE.erl
=> [Closes #353] Remove ratio parsing in reader

src/clj/clojure/core/server.clje, src/clj/clojure/main.clje, src/clj/clojure/repl.clje, src/erl/clj_reader.erl, src/erl/erlang/erlang.io.File.erl, src/erl/erlang/erlang.io.IPushbackReader.erl, src/erl/erlang/erlang.io.IReader.erl, src/erl/erlang/erlang.io.PushbackReader.erl, src/erl/erlang/erlang.io.StringReader.erl, src/erl/lang/clojerl.Keyword.erl, test/clj_reader_SUITE.erl, test/clojerl_Keyword_SUITE.erl, test/erlang_io_File_SUITE.erl, test/erlang_io_PushbackReader_SUITE.erl, test/erlang_io_StringReader_SUITE.erl
=> [Closes #358] Move unread from IReader to a new IPushbackReader protocol

include/clojerl.hrl, src/clj/clojure/core.clje, src/erl/lang/collections/clojerl.ChunkedCons.erl, src/erl/lang/collections/clojerl.Range.erl, src/erl/lang/collections/clojerl.TupleChunk.erl, src/erl/lang/collections/clojerl.Vector.ChunkedSeq.erl, src/erl/lang/collections/clojerl.Vector.erl, src/erl/lang/protocols/clojerl.IChunk.erl, src/erl/lang/protocols/clojerl.IChunkedSeq.erl, test/clojerl_ChunkedCons_SUITE.erl, test/clojerl_Range_SUITE.erl, test/clojerl_TupleChunk_SUITE.erl, test/clojerl_Vector_ChunkedSeq_SUITE.erl, test/erlang_io_PushbackReader_SUITE.erl
=> [Closes #115] Implement chunked seq

src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl, src/erl/clj_module.erl, src/erl/lang/clojerl.Var.erl, src/erl/lang/collections/clojerl.Map.erl, src/erl/lang/collections/clojerl.Set.erl, test/clj/benchmark/result.txt
=> [Closes #206] Improve apply for var

src/clj/clojure/core.clje, src/clj/clojure/main.clje, test/clj/clojure/test_clojure/compilation.clje, test/clj/clojure/test_clojure/main.clje
=> [Closes #371] Binary compile path

.gitignore, Makefile, test/clj/benchmark/report.clje, test/clj/benchmark/result.txt
=> [Closes #373] Print a table comparing the results

src/clj/clojure/core.clje, src/clj/clojure/instant.clje, src/erl/clj_rt.erl, src/erl/clj_utils.erl, src/erl/erlang/erlang.util.Date.erl, src/erl/lang/clojerl.String.erl, src/erl/lang/collections/clojerl.LazySeq.erl, src/erl/lang/collections/clojerl.Range.erl, src/erl/lang/collections/clojerl.SortedMap.erl, src/erl/lang/collections/clojerl.SortedSet.erl, src/erl/lang/collections/clojerl.Vector.erl, src/erl/rbdict.erl, test/clj/benchmark/report.clje, test/clj/clojure/test_clojure/clojure_instant.clje, test/clj/clojure/test_clojure/sequences.clje, test/clojerl_LazySeq_SUITE.erl, test/clojerl_Range_SUITE.erl, test/clojerl_String_SUITE.erl, test/erlang_util_Date_SUITE.erl
=> [Closes #261] Sort by

src/clj/clojure/core.clje, src/erl/clj_rt.erl, test/clj/benchmark/result.txt
=> [Closes #376] Avoid creating a type when using instance? and satisfies?

src/clj/clojure/core.clje, test/clj/benchmark/result.txt
=> [Closes #378] Remove arbitrary precision functions

Makefile, test/clj/benchmark/benchmark_runner.clje, test/clj/benchmark/result.txt
=> [Closes #384] Run benchmarks using clojure.main

Makefile, bin/flame-expr.sh, src/erl/clj_analyzer.erl, src/erl/clj_compiler.erl, src/erl/clj_emitter.erl, src/erl/clj_reader.erl, src/erl/clj_rt.erl, src/erl/lang/collections/clojerl.ChunkedCons.erl, src/erl/lang/collections/clojerl.Cons.erl, src/erl/lang/collections/clojerl.LazySeq.erl, src/erl/lang/collections/clojerl.List.erl, src/erl/lang/collections/clojerl.Map.erl, src/erl/lang/collections/clojerl.Range.erl, src/erl/lang/collections/clojerl.Set.erl, src/erl/lang/collections/clojerl.SortedMap.erl, src/erl/lang/collections/clojerl.TupleChunk.erl, src/erl/lang/collections/clojerl.TupleMap.erl, src/erl/lang/collections/clojerl.Vector.ChunkedSeq.erl, src/erl/lang/collections/clojerl.Vector.erl, test/clojerl_Range_SUITE.erl, test/clojerl_TupleChunk_SUITE.erl
=> [Closes #388] Avoid protocol resolution when possible

bootstrap/clojure.core.erl, include/clojerl.hrl, include/clojerl_int.hrl, src/erl/clj_analyzer.erl, src/erl/clj_compiler.erl, src/erl/clj_emitter.erl, src/erl/clj_module.erl, src/erl/clj_protocol.erl, src/erl/clj_reader.erl, src/erl/clj_rt.erl, src/erl/clj_utils.erl, src/erl/erlang/erlang.Map.erl, src/erl/lang/clojerl.Var.erl, src/erl/lang/collections/clojerl.Range.erl, src/erl/lang/collections/clojerl.Vector.ChunkedSeq.erl, src/erl/lang/collections/clojerl.Vector.erl, test/clj_analyzer_SUITE.erl, test/clj_reader_SUITE.erl, test/clojerl_Range_SUITE.erl
=> [Closes #363] Move internal definitions to internal header file

.appveyor.yml, .gitignore, .travis.yml, Makefile, c_src/Makefile, rebar.config, rebar.config.script
=> [Closes #387] Build on windows

src/clj/clojure/pprint/pretty_writer.clje, src/erl/clj_reader.erl, test/clj_reader_SUITE.erl
=> [Closes #394] Keep meta for generated symbols in syntax quote

src/erl/clj_analyzer.erl, test/clj_analyzer_SUITE.erl
=> [Closes #396] Keep tag for dot syntax

src/clj/clojure/core.clje, src/clj/clojure/pprint/cl_format.clje, src/clj/clojure/string.clje, src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl, src/erl/clojerl_cli.erl, src/erl/lang/clojerl.Default.erl, src/erl/lang/clojerl.Nil.erl, src/erl/lang/clojerl.String.erl, test/clojerl_Nil_SUITE.erl
=> [Closes #400] Use dot syntax in clojure.string

bin/clojerl, src/erl/clojerl_cli.erl, src/erl/lang/clojerl.String.erl
=> [Closes #404] Improve help text for bin/clojerl

src/erl/clj_compiler.erl
=> [#406] Don't delete cerl_evalN module (temp workaround)

bootstrap/clojure.core.erl, src/clj/clojure/core.clje, src/erl/clj_analyzer.erl, src/erl/clj_compiler.erl, src/erl/clj_emitter.erl, src/erl/clj_module.erl, src/erl/clj_rt.erl, src/erl/lang/clojerl.Keyword.erl, src/erl/lang/clojerl.Namespace.erl, src/erl/lang/clojerl.Var.erl, test/clj_analyzer_SUITE.erl, test/clojerl_Namespace_SUITE.erl, test/clojerl_Var_SUITE.erl
=> [Closes #407] Include imports and aliases

src/erl/clj_analyzer.erl, test/clj/examples/deftype.clje, test/clojerl_SortedMap_SUITE.erl, test/clojerl_SortedSet_SUITE.erl
=> [Closes #411] Import type during analysis of deftype so that it can be resolved

src/erl/clj_protocol.erl, src/erl/clojerl.erl
=> [Closes #413] Don't ensure modules on application start

src/clj/clojure/string.clje, src/erl/lang/clojerl.String.erl, test/clojerl_String_SUITE.erl
=> [Closes #415] Add replace to clojerl.String

bin/clojerl
=> [Closes #417] Use sh instead of bash

src/clojerl.app.src, src/erl/clj_emitter.erl, src/erl/clj_module.erl
=> [Closes #419] Add compiler application in .app

src/clj/clojure/core_print.clje, src/erl/clj_rt.erl, src/erl/erlang/erlang.List.erl, test/clojerl_LazySeq_SUITE.erl, test/clojerl_Range_SUITE.erl, test/clojerl_reader_ReaderConditional_SUITE.erl, test/erlang_List_SUITE.erl
=> [Closes #422] erlang.String fix IStringable implementation

src/clj/clojure/core_print.clje
=> [Closes #424] Build string and then write

src/clj/clojure/core.clje
=> [Closes #426] Build list instead of using seq

src/clj/clojure/core_print.clje, src/erl/clj_reader.erl, src/erl/clj_rt.erl, src/erl/erlang/erlang.List.erl
=> [Closes #422] Erlang string fix stringable implementation

.appveyor.yml, Makefile, bin/clojerl
=> [Closes #430] Keep non-processed arguments in a var

src/erl/clj_utils.erl, test/clj_compiler_SUITE.erl
=> [Closes #429] Check binary code in memory before going to the file

src/clj/clojure/core.clje, src/clj/clojure/pprint.clje, src/erl/lang/clojerl.Namespace.erl
=> [Closes #438] Warn when overriding var

README.md
Add link to the rebar3 repo and update the repo link.
Makes it easier for people trying it out the first time 😄
=> Update Building Instructions

dummy.clj, elvis.config, src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl, src/erl/clj_env.erl, src/erl/clj_utils.erl, src/erl/clojerl_expr.hrl, src/erl/lang/collections/clojerl.TupleMap.erl, test/clj_reader_SUITE.erl, test/clojerl_Atom_SUITE.erl
=> [Closes #437] Define expr type for analyzer

src/clj/clojure/core.clje
=> [#444] Fix version regex, don't fail on parsing version

README.md, src/clj/clojure/core.clje, test/clj/clojure/test_clojure/compilation.clje, test/clj/clojure/test_clojure/compilation/line_number_examples.clje, test/clj/clojure/test_clojure/def.clje, test/clj/clojure/test_clojure/logic.clje, test/clj/clojure/test_clojure/metadata.clje, test/clj/clojure/test_clojure/protocols.clje, test/clj/clojure/test_clojure/sequences.clje
=> [Closes #443] Remove references to long, auto-promoting and integer overflow 

test/clj/benchmark/benchmark_runner.clje, test/clj/benchmark/report.clje, test/clj/benchmark/result.txt
=> [Closes #448] Running benchmark fails

Makefile, test/clj/clojure/test_clojure/compilation.clje, test/clj/clojure/test_clojure/run_tests.clje, test/clj/examples/run_tests.clje
=> [Closes #447] Check test results

src/erl/clj_compiler.erl, src/erl/clj_env.erl, src/erl/clj_reader.erl, src/erl/clj_utils.erl
=> [Closes #250] Report time for read, analyze, emit & eval separately

Makefile, include/clojerl_int.hrl, src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl, src/erl/clj_module.erl, src/erl/clojerl_expr.hrl, test/clj/examples/fn.clje
=> [Fixes #453] Error when using fn with def

src/clj/clojure/core.clje, src/clj/clojure/core_deftype.clje, src/clj/clojure/data.clje, src/clj/clojure/main.clje, src/clj/clojure/pprint/cl_format.clje, src/clj/clojure/pprint/column_writer.clje, src/clj/clojure/pprint/dispatch.clje, src/clj/clojure/pprint/pretty_writer.clje, src/clj/clojure/repl.clje, src/clj/clojure/stacktrace.clje, src/clj/clojure/test.clje, test/clj/clojure/test_clojure/compilation.clje, test/clj/clojure/test_clojure/def.clje, test/clj/clojure/test_clojure/multimethods.clje, test/clj/clojure/test_clojure/pprint/test_pretty.clje, test/clj/clojure/test_clojure/protocols.clje, test/clj/clojure/test_clojure/reader.cljc, test/clj/clojure/test_clojure/sequences.clje, test/clj/clojure/test_clojure/test.clje, test/clj/clojure/test_helper.clje
=> [Fixes #455] Replace references to class for type

src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl, test/clj/examples/try.clje, test/clj_analyzer_SUITE.erl
=> [Closes #436] Allow symbols in error type position for catch clauses

bootstrap/clojure.core.erl, include/clojerl_int.hrl, src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl, src/erl/clj_protocol.erl, src/erl/clj_reader.erl, src/erl/clj_rt.erl, src/erl/clj_utils.erl, src/erl/lang/clojerl.ExceptionInfo.erl, src/erl/lang/clojerl.Namespace.erl, src/erl/lang/clojerl.Var.erl, src/erl/lang/collections/clojerl.TupleMap.erl
=> [Closes #460] Replace error generating function calls for Erlang macros

src/erl/clj_emitter.erl, test/clj/examples/case.clje
=> [Closes #464] Case duplicate_var error

src/clj/clojure/erlang/io.clje, src/erl/clojerl_cli.erl
=> [Closes #463] Process file options

Makefile, bin/clje, bin/clojerl, src/erl/clojerl_cli.erl
=> [#467] Similar CLI to clojure

src/erl/clj_emitter.erl, src/erl/clj_module.erl
=> [Closes #469] Emit local calls for recursive calls in fake funs

src/erl/clj_utils.erl, src/erl/clojerl_cli.erl
=> [Closes #475] Don't crash when an error occurs while loading

rebar.config, rebar.config.script, src/erl/lang/clojerl.Atom.erl
=> [Closes #421] Use ETS compare-and-swap for Atoms when available

bin/clojerl, src/erl/clj_utils.erl
=> [Closes #478] Expand extra arguments differently

src/clj/clojure/core.clje, src/clj/clojure/core/protocols.clje, src/erl/clj_analyzer.erl, src/erl/clj_reader.erl, src/erl/clj_rt.erl, src/erl/lang/collections/clojerl.ChunkedCons.erl, src/erl/lang/collections/clojerl.Cons.erl, src/erl/lang/collections/clojerl.LazySeq.erl, src/erl/lang/collections/clojerl.List.erl, src/erl/lang/collections/clojerl.Map.erl, src/erl/lang/collections/clojerl.Range.erl, src/erl/lang/collections/clojerl.TupleMap.erl, src/erl/lang/collections/clojerl.Vector.ChunkedSeq.erl, src/erl/lang/collections/clojerl.Vector.erl, src/erl/lang/protocols/clojerl.IErl.erl, test/clojerl_ChunkedCons_SUITE.erl, test/clojerl_Cons_SUITE.erl, test/clojerl_LazySeq_SUITE.erl, test/clojerl_List_SUITE.erl, test/clojerl_Map_SUITE.erl, test/clojerl_Range_SUITE.erl, test/clojerl_TupleMap_SUITE.erl, test/clojerl_Vector_ChunkedSeq_SUITE.erl, test/clojerl_Vector_SUITE.erl
=> [#320] Protocol for conversion of collections to Erlang collections

bin/clojerl, src/erl/clj_compiler.erl
=> [Closes #481] Fix bug introduced by #478

src/erl/clj_utils.erl
=> [Closes #483] Handle the case when args are provided

src/clj/clojure/core.clje, src/clj/clojure/repl.clje, src/erl/clj_rt.erl, src/erl/clj_utils.erl
=> [Closes #485] Avoid failure for source

src/erl/clj_emitter.erl, test/clj/examples/fn.clje
=> [Closes #490] Funs Core Erlang generation bug

include/clojerl_int.hrl, src/clj/clojure/core.clje, src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl, src/erl/clj_utils.erl, src/erl/lang/clojerl.Namespace.erl
=> [Closes #489] Inlining

bin/flame-expr.sh, src/clj/clojure/core.clje, src/clj/clojure/core_deftype.clje, src/erl/lang/collections/clojerl.TupleChunk.erl, src/erl/lang/collections/clojerl.Vector.ChunkedSeq.erl, test/clj_analyzer_SUITE.erl, test/clojerl_Vector_ChunkedSeq_SUITE.erl
=> [Closes #487] Rename reduce1 and into1 so that the final ones get used in the end

include/clojerl_int.hrl, src/erl/clj_reader.erl, src/erl/clj_utils.erl, test/clj/benchmark/benchmark_runner.clje
=> [Closes #493] Compile regular expressions for numbers and run them only once

bootstrap/clojure.core.erl, src/erl/lang/clojerl.Var.erl, test/clj/benchmark/result.txt
=> [#495] Fix bug introduced binary_to_atom usage reduction

src/clj/clojure/core.clje
=> [Fixes #498] Fix order of arguments and use satisfies? instead of instance?

src/erl/lang/collections/clojerl.Range.erl, src/erl/lang/collections/clojerl.Vector.ChunkedSeq.erl, test/clojerl_Vector_ChunkedSeq_SUITE.erl
=> [Closes #500] Complete test coverage clojerl.Vector.ChunkedSeq

src/clj/clojure/core.clje, src/erl/erlang/erlang.Map.erl, test/erlang_Map_SUITE.erl
=> [Closes #502] Return Erlang list of Erlang tuples

src/erl/lang/clojerl.Namespace.erl, test/clojerl_Namespace_SUITE.erl
=> [Closes #509] Don't error if the var is the same

Makefile, src/clj/clojure/core_deftype.clje, src/erl/clj_compiler.erl, src/erl/clj_emitter.erl, src/erl/clj_utils.erl, test/clj_compiler_SUITE.erl
=> [Closes #507] Return output files from compile_file function

src/erl/lang/collections/clojerl.Vector.RSeq.erl, src/erl/lang/collections/clojerl.Vector.erl, src/erl/lang/protocols/clojerl.IColl.erl, src/erl/lang/protocols/clojerl.ICounted.erl, src/erl/lang/protocols/clojerl.IEquiv.erl, src/erl/lang/protocols/clojerl.IErl.erl, src/erl/lang/protocols/clojerl.IHash.erl, src/erl/lang/protocols/clojerl.IMeta.erl, src/erl/lang/protocols/clojerl.IReversible.erl, src/erl/lang/protocols/clojerl.ISeq.erl, src/erl/lang/protocols/clojerl.ISeqable.erl, src/erl/lang/protocols/clojerl.ISequential.erl, src/erl/lang/protocols/clojerl.IStringable.erl, test/clojerl_Vector_RSeq_SUITE.erl, test/clojerl_Vector_SUITE.erl
=> [Closes #506] Implement IReversible for vectors

src/erl/lang/clojerl.Var.erl
=> [Closes #512] Avoid calling maps:get/[2,3]

Makefile, src/clj/clojure/test.clje, src/erl/clj_analyzer.erl, src/erl/clj_module.erl, src/erl/lang/clojerl.Var.erl, test/clj/benchmark/result.txt, test/clj_compiler_SUITE.erl
=> [Closes #156] Mark vars inside fake_funs and when macroexpanding

src/clj/clojure/core.clje
=> [Fix #519] Use fully qualified call to clojure.core/list

src/erl/clj_emitter.erl
=> [Closes #524] Improve error message when calling anonymous functions with badarity

src/clj/clojure/main.clje, src/erl/clj_analyzer.erl, src/erl/clj_env.erl, test/clj/clojure/test_clojure/compilation.clje, test/clj_analyzer_SUITE.erl
=> [Closes #523] Check if inside def when there is an unresolved symbol

scripts/protocols/function.clje, src/clj/clojure/core.clje, src/erl/clj_module.erl, src/erl/lang/clojerl.Namespace.erl, src/erl/lang/protocols/clojerl.IMeta.erl, src/erl/lang/protocols/clojerl.IReference.erl, test/clojerl_Namespace_SUITE.erl
=> [#516] ns docstring lost

src/erl/erlang/erlang.List.erl, src/erl/lang/protocols/clojerl.ILookup.erl, test/erlang_List_SUITE.erl
=> [Closes #530] Implement ILookup for Erlang lists

src/clj/clojure/test.clje
=> [#532] Get the var's name from its meta

src/clj/clojure/core.clje
=> [Fixes #534] Always provide the Var and not its bound value

src/clj/clojure/core.clje, src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl, src/erl/clojerl_expr.hrl, test/clj/examples/try.clje, test/clj_analyzer_SUITE.erl
=> [Closes #536] Allow two arguments for throw, the second will be the stacktrace

src/erl/erlang/erlang.util.UUID.erl, test/erlang_util_UUID_SUITE.erl
Add random/3 which takes the integer to create the UUID.
=> Represent UUID with lower case letters

src/clj/clojure/core.clje, src/erl/clj_reader.erl, src/erl/clj_rt.erl
=> [Fixes #541] Check for a binary with a single utf8 character in char?

src/erl/clj_reader.erl, test/clj_reader_SUITE.erl
=> [Fixes #525] Handle multiple contiguous discards

bin/clojerl, src/erl/clj_emitter.erl, src/erl/clojerl_cli.erl, test/clj/examples/letfn.clje
=> [Closes #547] letrec workaround ERL-658

.travis.yml, include/clojerl_int.hrl, rebar.config, rebar.config.script, src/clj/clojure/core.clje, src/clj/clojure/main.clje, src/clj/clojure/repl.clje, src/clj/clojure/stacktrace.clje, src/clj/clojure/test.clje, src/erl/clj_analyzer.erl, src/erl/clj_compiler.erl, src/erl/clj_emitter.erl, src/erl/clj_reader.erl, src/erl/clj_utils.erl, src/erl/clojerl_cli.erl, src/erl/clojerl_expr.hrl, src/erl/lang/clojerl.Var.erl, test/clj/clojure/test_clojure/compilation.clje, test/clj/examples/try.clje, test/clj_analyzer_SUITE.erl
=> [Closes #545] OTP 21 compatible

src/clj/clojure/core.clje, src/clj/clojure/core_deftype.clje, src/erl/clj_analyzer.erl, src/erl/clj_rt.erl, src/erl/erlang/erlang.Type.erl
=> [Fixes #552] Avoid calling clj_rt:type[_module]/1

src/erl/clj_murmur3.erl, test/clojerl_Map_SUITE.erl
=> [Fixes #555] Change the initial hash value for unordered collections

rebar.config, src/clj/clojure/edn.clje, src/clj/clojure/instant.clje, src/clj/clojure/uuid.clje, src/erl/clj_edn.erl, src/erl/clj_reader.erl, src/erl/clj_rt.erl, src/erl/lang/clojerl.Namespace.erl, test/clj/clojure/test_clojure/edn.clje, test/clj/clojure/test_clojure/generators.clje, test/clojerl_Namespace_SUITE.erl
=> [Closes #550] Implements clojure.edn

src/clj/clojure/core.clje
=> [Fixes #573] Generate better names for defmethod implementation vars

src/erl/clj_rt.erl, src/erl/lang/clojerl.Keyword.erl, test/clj/clojure/test_clojure/compilation.clje, test/clj/clojure/test_clojure/compilation/line_number_examples.clje
=> [Fixes #570] Return nil or default value for general get

rebar.config, src/erl/clj_analyzer.erl
=> [Closes #571] Warn when symbol is not resolved as a type 

Makefile, bin/clje
=> [Closes #577] make repl fails on ubuntu

src/erl/clj_rt.erl, test/clj_rt_SUITE.erl
=> [Fixes #579] Memory leak on clj_rt:print/1

src/clj/clojure/core_print.clje, src/erl/clj_analyzer.erl, src/erl/lang/clojerl.Namespace.erl, test/clojerl_Namespace_SUITE.erl
=> [Closes #581] str for namespaces

src/clj/clojure/core.clje, src/erl/clj_rt.erl, test/clj/clojure/test_clojure/numbers.clje
=> [Fixes #583] divide arity 1 fails

.appveyor.yml, .travis.yml
=> [Closes #585] Build with OTP 21.1

src/erl/clj_hash_collision.erl, test/clj/clojure/test_clojure/protocols.clje, test/clojerl_Set_SUITE.erl
=> [Fixes #590] set hash collisions generate problems

scripts/examples/case.clje, scripts/examples/guard.clje, src/clj/clojure/core.clje, src/clj/clojure/test.clje, src/clj/clojure/walk.clje, src/erl/clj_utils.erl, src/erl/lang/collections/clojerl.Set.erl, src/erl/rbdict.erl, test/clj/clojure/test_clojure/clojure_walk.clje, test/clj/clojure/test_clojure/control.clje, test/clj_reader_SUITE.erl
=> [#587] clojure.test-clojure.clojure-walk, clojure.test-clojure.control

test/clj/clojure/test_clojure/evaluation.clje
=> [#587] Add clojure.test-clojure.evaluation

test/clj/clojure/test_clojure/evaluation.clje, test/clj/clojure/test_clojure/fn.clje
=> [#587] Migrate clojure.test-clojure.fn

src/erl/lang/clojerl.Namespace.erl, test/clj/clojure/test_clojure/ns_libs.clje
=> [#587] Add clojure.test-clojure.ns-libs

test/clj/clojure/test_clojure/other_functions.clje
=> [#587] Add clojure.test-clojure.other-functions

scripts/generate-protocols, src/clj/clojure/core.clje, src/erl/clj_analyzer.erl, src/erl/erlang/erlang.io.ICloseable.erl, src/erl/erlang/erlang.io.IReader.erl, src/erl/erlang/erlang.io.IWriter.erl, src/erl/erlang/erlang.util.Date.erl, src/erl/lang/protocols/clojerl.IAssociative.erl, src/erl/lang/protocols/clojerl.IChunkedSeq.erl, src/erl/lang/protocols/clojerl.IColl.erl, src/erl/lang/protocols/clojerl.ICounted.erl, src/erl/lang/protocols/clojerl.IDeref.erl, src/erl/lang/protocols/clojerl.IEquiv.erl, src/erl/lang/protocols/clojerl.IErl.erl, src/erl/lang/protocols/clojerl.IError.erl, src/erl/lang/protocols/clojerl.IFn.erl, src/erl/lang/protocols/clojerl.IHash.erl, src/erl/lang/protocols/clojerl.IIndexed.erl, src/erl/lang/protocols/clojerl.ILookup.erl, src/erl/lang/protocols/clojerl.IMap.erl, src/erl/lang/protocols/clojerl.IMeta.erl, src/erl/lang/protocols/clojerl.INamed.erl, src/erl/lang/protocols/clojerl.IReduce.erl, src/erl/lang/protocols/clojerl.ISeq.erl, src/erl/lang/protocols/clojerl.ISeqable.erl, src/erl/lang/protocols/clojerl.ISequential.erl, src/erl/lang/protocols/clojerl.IStringable.erl, test/clj/clojure/test_clojure/predicates.clje
=> [#587] migrate clojure test clojure predicates

src/clj/clojure/core.clje, src/erl/lang/collections/clojerl.ChunkBuffer.erl, test/clj/clojure/test_clojure/for.clje
=> [#587] migrate clojure test clojure for

src/clj/clojure/repl.clje, test/clj/clojure/test_clojure/repl.clje, test/clj/clojure/test_clojure/repl/example.clje
=> [#587] Migrate clojure.test-clojure.repl

src/erl/clj_rt.erl, src/erl/erlang/erlang.List.erl, src/erl/erlang/erlang.Map.erl, src/erl/erlang/erlang.Tuple.erl, src/erl/lang/clojerl.Namespace.erl, src/erl/lang/collections/clojerl.ChunkedCons.erl, src/erl/lang/collections/clojerl.Cons.erl, src/erl/lang/collections/clojerl.List.erl, src/erl/lang/collections/clojerl.Map.erl, src/erl/lang/collections/clojerl.Range.erl, src/erl/lang/collections/clojerl.Set.erl, src/erl/lang/collections/clojerl.SortedMap.erl, src/erl/lang/collections/clojerl.SortedSet.erl, src/erl/lang/collections/clojerl.TupleMap.erl, src/erl/lang/collections/clojerl.Vector.ChunkedSeq.erl, src/erl/lang/collections/clojerl.Vector.RSeq.erl, src/erl/lang/collections/clojerl.Vector.erl, test/clj/clojure/test_clojure/rt.clje, test/clj_rt_SUITE.erl, test/clojerl_Namespace_SUITE.erl
=> [#587] migrate clojure.test-clojure.rt

test/clj/clojure/test_clojure/refs.clje
=> [#587] Add clojure.test-clojure.refs (which is empty)

src/erl/lang/collections/clojerl.Vector.ChunkedSeq.erl, src/erl/lang/collections/clojerl.Vector.erl, test/clj/clojure/test_clojure/vectors.clje, test/clojerl_Vector_SUITE.erl
=> [#587] Migrate clojure test clojure vectors

test/clj/clojure/test_clojure/special.clje
=> [#587] Migrate clojure.test-clojure.special

src/clj/clojure/test.clje, src/erl/lang/clojerl.Namespace.erl, test/clj/clojure/test_clojure/test_fixtures.clje
=> [#587] migrate clojure.test-clojure.test-fixtures

src/clj/clojure/core_print.clje, src/clj/clojure/main.clje, test/clj/clojure/test_clojure/printer.clje
=> [#587] migrate clojure test clojure printer

src/clj/clojure/core.clje, test/clj/clojure/test_clojure/vectors.clje
=> [Fixes #562] Support ISeqable for Eduction through an EductionSeq type

rebar.config, scripts/examples/deftype.clje, src/erl/clj_emitter.erl
=> [Closes #616] extend-type fails for default

README.md
=> [#618] Improve documentation for Getting Started

src/clj/clojure/core.clje, src/erl/clojerl_sup.erl, src/erl/erlang/erlang.io.ICloseable.erl, src/erl/lang/clojerl.Delay.erl, src/erl/lang/protocols/clojerl.IDeref.erl, src/erl/lang/protocols/clojerl.IEquiv.erl, src/erl/lang/protocols/clojerl.IHash.erl, src/erl/lang/protocols/clojerl.IStringable.erl, test/clj/clojure/test_clojure/delays.clje
=> [#90] Delay

scripts/benchmark/result.txt, src/erl/lang/collections/clojerl.Vector.erl
=> [Closes #625] Improve perf reduce vector

scripts/benchmark/report.md, scripts/benchmark/result.txt, src/clj/clojure/core.clje, src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl, src/erl/clojerl_expr.hrl, src/erl/erlang/erlang.Fn.erl, src/erl/lang/clojerl.Fn.erl, src/erl/lang/clojerl.TransducerSeq.erl, src/erl/lang/collections/clojerl.LazySeq.erl, src/erl/lang/protocols/clojerl.IFn.erl, src/erl/lang/protocols/clojerl.IHash.erl, src/erl/lang/protocols/clojerl.IStringable.erl, test/clj/clojure/test_clojure/generators.clje, test/clojerl_ChunkedCons_SUITE.erl, test/clojerl_Cons_SUITE.erl, test/clojerl_LazySeq_SUITE.erl, test/clojerl_List_SUITE.erl, test/clojerl_Range_SUITE.erl, test/clojerl_Vector_ChunkedSeq_SUITE.erl, test/clojerl_Vector_SUITE.erl, test/erlang_List_SUITE.erl
=> [Closes #631] improve performance apply anon fn

.travis.yml, src/erl/clj_compiler.erl, src/erl/clj_emitter.erl, src/erl/clojerl_cli.erl
=> [Closes #634] Erlang/OTP 22.0

scripts/benchmark/report.md, scripts/benchmark/result.txt, src/erl/lang/clojerl.String.erl, src/erl/lang/collections/clojerl.List.erl, src/erl/lang/collections/clojerl.StringSeq.erl, src/erl/lang/protocols/clojerl.IColl.erl, src/erl/lang/protocols/clojerl.ICounted.erl, src/erl/lang/protocols/clojerl.IEquiv.erl, src/erl/lang/protocols/clojerl.IHash.erl, src/erl/lang/protocols/clojerl.ISeq.erl, src/erl/lang/protocols/clojerl.ISeqable.erl, src/erl/lang/protocols/clojerl.ISequential.erl, src/erl/lang/protocols/clojerl.IStringable.erl, test/clojerl_List_SUITE.erl, test/clojerl_StringSeq_SUITE.erl, test/clojerl_String_SUITE.erl
=> [Closes #648] StringSeq

src/clj/clojure/core_print.clje, src/clj/clojure/main.clje, src/erl/clj_edn.erl, src/erl/clj_reader.erl, src/erl/clj_rt.erl, src/erl/lang/collections/clojerl.Map.erl, src/erl/lang/collections/clojerl.StringSeq.erl, test/clj/clojure/test_clojure/printer.clje, test/clj/clojure/test_clojure/reader.cljc
=> [Closes #325] Map namespace syntax

rebar.config, src/clojerl.app.src
=> [#652] Modify clojerl.app.src to be able to publish to package

README.md, src/clojerl.app.src
=> [#652] Useful links in clojerl.app.src

README.md
=> [#652] Hex badge link

Makefile, scripts/examples/receive.clje, src/erl/clj_compiler.erl, src/erl/core_eval.erl, test/core_eval_SUITE.erl
=> [#406] core erlang interpreter

src/erl/clj_reader.erl, src/erl/clj_rt.erl, test/clj_analyzer_SUITE.erl
=> [Closes #659] Reset gensym id in top level reader functions just before reading forms

.travis.yml
=> [Closes #663] Specify trusty

README.md
=> [#667] Make clojerl.org link more visible in README

test/clj/erlang/test_erlang/behaviours.clje
=> [#661] Erlang behaviour tests

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
=> [#673] Add issue templates

src/erl/clj_rt.erl, src/erl/rbdict.erl, test/clj/clojure/test_clojure/data_structures.clje
Fix handling of compare functions.
Fixes #670 .
=> [#670] Fix handling of compare functions

Makefile, rebar.config, src/erl/clojerl.erl
=> [#677] Generate cover reports

src/erl/lang/clojerl.Var.erl
Avoid going through the generic `clj_rt:str/1` function in `'clojerl.Var':dynamic_bindings/[1,2]`.
=> Use var specific str function

src/erl/clj_compiler.erl
Output `.core` file to the same dir as specified for `.beam`.
Fixes #694
=> [#694] Output .core file to the same dir as specified for .beam

src/erl/clj_analyzer.erl, test/clj_compiler_SUITE.erl
Always resolve in-ns and ns
Fixes #697
=> [#697] Always resolve in-ns and ns

README.md
=> [#707] Google group and working link to Slack

src/erl/clj_analyzer.erl
Include form's line and column information if its macroexpansion fails.
Fixes #706.
For the following file `error_reporting.clje`:
```
(ns error-reporting)
(defn- home-dir
"The user's home directory."
nil)
```
This is what the result of trying to compile looks like:
```
$ bin/clojerl error_reporting.clje
[error] clojerl.BadArgumentError: error_reporting.clje:3:1: Parameter declaration "" should be a vector
clojure.core/-assert-valid-fdecl/1-anon__1205/1-0-.2 (/Users/juan.facorro/dev/clojerl/clojerl/_build/default/lib/clojerl/src/clj/clojure/core.clje:5893)
clojure.core/-map/2-anon__309/0-0-.2 (/Users/juan.facorro/dev/clojerl/clojerl/_build/default/lib/clojerl/src/clj/clojure/core.clje:2205)
clojerl.LazySeq/seq.1 (/Users/juan.facorro/dev/clojerl/clojerl/src/erl/lang/collections/clojerl.Lazy …
```
=> [#706] Report location of error during macroexpansion

src/erl/clj_scope.erl, src/erl/lang/clojerl.Var.erl, test/clojerl_Var_SUITE.erl
…and `clojerl.Var:is_bound/1`.
Fixed #718
=> [#718] Fix implementation and update tests for clojerl.Var:has_root/1

src/erl/clojerl_app.erl
=> [#728] Return top level supervisor pid

bin/clojerl, bin/clojerl.bat, src/erl/clj_compiler.erl, src/erl/clojerl_cli.erl
=> [#730] Add option to compile to BEAM assembly

src/erl/lang/clojerl.Namespace.erl, test/clojerl_Namespace_SUITE.erl
=> [#732] Fix bug when checking for overriden vars

bin/clojerl
=> [#741] Use pattern matching in case

src/erl/clj_multimethod.erl
=> [#745] Munge namespace name for multimethod's map

Makefile, src/clj/clojure/core.clje
=> [#749] Include original stacktrace when throwing error

src/clj/clojure/core.clje
=> [#749] Provide stacktrace to throw

src/erl/clj_analyzer.erl, src/erl/core_eval.erl
=> [#752] Improve error reporting for erl-binary*

scripts/examples/pattern.clje, src/erl/clj_analyzer.erl, src/erl/clj_emitter.erl
=> [#755] Don't parse :size as a pattern

.travis.yml, Makefile, src/erl/clj_emitter.erl
=> [#753] Compile with OTP 23

src/clj/clojure/main.clje, src/erl/clojerl_app.erl
=> [#758] Starting REPL from shell fails

src/clj/clojure/main.clje, src/erl/erlang/erlang.io.StringReader.erl, src/erl/erlang/erlang.io.StringWriter.erl, test/erlang_io_StringReader_SUITE.erl
=> [#762] REPL from Erlang shell outputs extra characters

rebar.config
=> [#764] Remove pre-hook

rebar.config
=> [#771] Bump rebar3_clojerl version to 0.8.4

src/clj/clojure/core.clje, src/clj/clojure/edn.clje, src/erl/clj_analyzer.erl, src/erl/clj_behaviour.erl, src/erl/clj_cache.erl, src/erl/clj_compiler.erl, src/erl/clj_edn.erl, src/erl/clj_emitter.erl, src/erl/clj_emitter_pattern.erl, src/erl/clj_env.erl, src/erl/clj_hash_collision.erl, src/erl/clj_module.erl, src/erl/clj_multimethod.erl, src/erl/clj_murmur3.erl, src/erl/clj_protocol.erl, src/erl/clj_reader.erl, src/erl/clj_rt.erl, src/erl/clj_scope.erl, src/erl/clj_utils.erl, src/erl/clj_vector.erl, src/erl/clojerl.erl, src/erl/clojerl_app.erl, src/erl/clojerl_cli.erl, src/erl/clojerl_sup.erl, src/erl/core_eval.erl, src/erl/rbdict.erl
=> [#766] Add documentation

.travis.yml, README.md
=> [#776] Remove support for Erlang/OTP 18.3

README.md
=> [#783] GitHub Actions build badge

src/erl/clj_analyzer.erl, test/clj/clojure/test_clojure/compilation.clje
=> [#786] Set expr context where missing

src/clj/clojure/core.clje, src/erl/clj_reader.erl, src/erl/erlang/erlang.Map.erl, test/clj/clojure/test_clojure/reader.cljc
=> [#788] compilation error with tuples in syntax quote

.github/workflows/build.yml
=> [#791] Add Erlang/OTP 24.0 to CI build

src/erl/clj_emitter.erl, src/erl/core_eval.erl, test/core_eval_SUITE.erl
=> [#796] Correctly handle throw expression in try expression through core_eval

src/clj/clojure/core.clje, src/erl/clj_analyzer.erl, test/clj/clojure/test_clojure/macros.clje
=> [#800] macro resolved instead of local

src/clj/clojure/core/reducers.clje, src/clj/clojure/core_deftype.clje, src/clj/clojure/pprint/cl_format.clje, src/clj/clojure/pprint/column_writer.clje, src/clj/clojure/pprint/pretty_writer.clje, src/erl/clj_analyzer.erl, test/clj/clojure/test_clojure/protocols.clje, test/clj/clojure/test_clojure/sequences.clje, test/clj/clojure/test_clojure/vectors.clje
=> [#802] Implement reify

src/clj/clojure/core_deftype.clje
=> [#802] Ensure that reify implements IStringable and IHash

src/clj/clojure/core_deftype.clje, src/erl/clj_analyzer.erl
=> [#803] reify implement IMeta

src/clj/clojure/core.clje, src/erl/clj_multimethod.erl, test/clj/clojure/test_clojure/multimethods.clje, test/clj_multimethod_SUITE.erl
=> [#808] multi-method dispatch fn

src/erl/clj_multimethod.erl
=> [#808] Ensure the var is not marked as fake

src/erl/clj_analyzer.erl, src/erl/clj_module.erl, src/erl/clj_multimethod.erl
=> [#808] Ensure false fake_fun in the vars in metadata

.gitpod.yml
=> [#812] Add gitpod configuration file

Makefile, rebar.config
=> [#814] Create docs profile which includes rebar3_docs plugin

.github/workflows/build.yml, rebar.config
=> [#814] Bump rebar3_clojerl plugin

.gitpod.Dockerfile, .gitpod.yml
=> [#820] Use custom dockerfile

.gitattributes, .github/workflows/build.yml, Makefile, scripts/run-test-generative
=> [#816] Add windows platform in CI pipeline

.appveyor.yml, .github/workflows/build.yml
=> [#816] Remove AppVeyor

src/erl/clj_reader.erl
=> [#826] reader unexpected value after invalid token

src/erl/erlang/erlang.io.PushbackReader.erl
=> [#828] Keep the previous at_line_start value to restore it when char is unread

scripts/benchmark/compare.cljc
=> [#839] Handle 0 as the measured time for clj

.github/ISSUE_TEMPLATE/question.md, README.md, src/clojerl.app.src
=> [#849] Update domains
