- src/clj/clojure/instant.clje
- src/erl/erlang/erlang.util.Date.erl
- test/clj/clojure/test_clojure/clojure_instant.clje
- test/clj/clojure/test_clojure/reader.cljc
- test/clj_reader_SUITE.erl
If merged, closes #262. 
- Adds a new type, `erlang.util.Date`, following the template provided by `erlang.util.Regex` and `erlang.util.UUID`, also mirroring the `java.util.*` classes.
- The type comes with `equiv` and `hash`. I didn't add `str` because it involved more complicated date printing (month names, etc.)
- Uses the new type in the reader.
- Dispatches off the type on `print-method`.
I don't write much Erlang, so please forgive me for any obvious blunders. If you can please point them out, I'll correct them.
> clojure.instant: add erlang.util.Date

- src/erl/lang/collections/clojerl.Vector.erl
- test/clojerl_Vector_SUITE.erl
> [Fixes #538] rseq return nil for empty vectors

- src/clj/clojure/instant.clje
- src/clj/clojure/uuid.clje
> [Fixes #558] Move print-method impls for UUID and Date to clojure.core

- Makefile
- rebar.config
- scripts/benchmark/report.clje
- scripts/benchmark/report.md
- scripts/benchmark/result.txt
- src/erl/clj_vector.erl
- src/erl/lang/collections/clojerl.TupleChunk.erl
- src/erl/lang/collections/clojerl.Vector.ChunkedSeq.erl
- src/erl/lang/collections/clojerl.Vector.RSeq.erl
- src/erl/lang/collections/clojerl.Vector.erl
- test/clojerl_Vector_ChunkedSeq_SUITE.erl
- test/clojerl_Vector_RSeq_SUITE.erl
#628
The benchmark for the `pop` operation results in worse times because it tests the edge case when a node in the tree data structure gets removed. The implementation for `array` in Erlang does not resize the tree when calling `array:resize/2` with a lower number (see [here](https://github.com/erlang/otp/blob/master/lib/stdlib/src/array.erl#L504)).
This is the result of comparing various operations of  `clj_vector` vs. `array`:
```
clje.user=> (foo/compare-creation)
compare-creation with 0
[], (array/from_list coll), 10000 runs, 0 msecs
[], (clj_vector/new coll), 10000 runs, 0 msecs
compare-creation with 100
[], (array/from_list coll), 10000 runs, 28 msecs
[], (clj_vector/new coll), 10000 runs, 28 msecs
compare-creation with 1000
[], (array/from_list coll), 10000 runs, 208 msecs
[], …
```
> [#628] Experiment with better vector implementation

- bootstrap/clojure.core.erl
- scripts/examples/fn.clje
- src/erl/clj_analyzer.erl
- src/erl/clj_emitter.erl
- src/erl/clojerl_expr.hrl
- src/erl/lang/clojerl.Var.erl
The function call will throw a function undefined error during runtime,
unless the var is dynamic and is bound to a different var. The compiler
could generate a compilation error, but this is not what the Clojure
compiler does in this case, so we stick to that behavior.
Fix #679.
> [#679] Emit a remote call to the var when the arity used does not exist

- src/erl/lang/collections/clojerl.Cons.erl
- src/erl/lang/protocols/clojerl.IReduce.erl
- test/clojerl_Cons_SUITE.erl
Don't implement the `IReduce` protocol for `Cons` cells. Clojure JVM does not do so, it seems to bring no benefits and it was the source of the related bug.
Fixes #682.
> [#682] Remove IReduce implementation from clojerl.Cons

- scripts/examples/case.clje
- scripts/examples/receive.clje
- scripts/examples/try.clje
- src/erl/clj_analyzer.erl
- src/erl/clj_emitter.erl
- src/erl/clj_emitter_pattern.erl
- src/erl/clj_env.erl
- src/erl/clj_scope.erl
- src/erl/core_eval.erl
- test/core_eval_SUITE.erl
Introduces the consideration of locals with the same name as the used variables in patterns. This **applies** to `catch`, `case*` and `receive*` expressions. 
It **does not** apply to `let*` and `loop*` expressions, where new bindings will be created even if the symbol's name is the same. Both `(let* [x 1 x 2] x)` and `(loop* [x 1 x 2] x)` are valid expressions and will return `2`.
Before this PR the patterns that used a variable with a name of an existing local, wheren't taking the value of the local into consideration.
Fixes #684.
> [#684] Bound value not used in pattern matching

- scripts/examples/case.clje
- src/erl/clj_emitter_pattern.erl
Fixes a small bug when emitting patterns, existing locals must be provided as an ordered set.
Related to #684.
> [#684] List of known variable must be ordset when emitting pattern

- .gitignore
- bootstrap/clojure.core.erl
- include/clojerl_int.hrl
- src/clj/clojure/core.clje
- src/erl/clojerl_sup.erl
- src/erl/erlang/erlang.io.ICloseable.erl
- src/erl/erlang/erlang.util.CountDownLatch.erl
- src/erl/lang/clojerl.Agent.Server.erl
- src/erl/lang/clojerl.Agent.erl
- src/erl/lang/protocols/clojerl.IDeref.erl
- src/erl/lang/protocols/clojerl.IEquiv.erl
- src/erl/lang/protocols/clojerl.IHash.erl
- src/erl/lang/protocols/clojerl.IMeta.erl
- src/erl/lang/protocols/clojerl.IReference.erl
- src/erl/lang/protocols/clojerl.IStringable.erl
- test/clj/clojure/test_clojure/agents.clje
- test/clj_test_utils.erl
- test/clojerl_Agent_SUITE.erl
- test/clojerl_Atom_SUITE.erl
Implements the agent abstraction. Watches are missing, but they will be added with #689.
There is currently no plan to implement Refs so this PR removes Refs functions from `clojure.core`.
Related to #117.
> [#117] Agents

- src/clj/clojure/core/server.clje
- Don't print out messages. 
- Use `clojure.edn`.
Fixes #691
> [#691] Remove printed messages

- scripts/examples/case.clje
- src/erl/clj_analyzer.erl
- src/erl/clj_emitter.erl
- src/erl/clojerl_expr.hrl
Correctly pattern match when multiple bindings have the same name.
Related #684
> [#684] Use name of shadowed local in pattern matching

- bootstrap/clojure.core.erl
- src/clj/clojure/core.clje
- src/clj/clojure/main.clje
- src/clj/clojure/pprint/dispatch.clje
- src/clj/clojure/pprint/utilities.clje
- src/erl/clj_compiler.erl
- src/erl/clj_rt.erl
- src/erl/clj_utils.erl
- src/erl/clojerl.erl
- test/clj/clojure/test_clojure/metadata.clje
- Create clje.user on application initialization.
- Load `user.clje` script if it is present in the code path.
- Start socket REPL servers of there are any `clojure.server.*` environment variables defined.
Fixes #609
> [#699] Create clje.user on init

- Makefile
- bin/clojerl
- scripts/run-test-generative
- src/clj/clojure/core.clje
- src/clj/clojure/instant.clje
- src/clj/clojure/uuid.clje
- src/clojerl.app.src
- src/erl/clj_murmur3.erl
- src/erl/clojerl.erl
- src/erl/clojerl_app.erl
- src/erl/erlang/erlang.io.File.erl
- test/clj/clojure/test_clojure/api.clje
- test/clj/clojure/test_clojure/numbers.clje
- test/clj/clojure/test_clojure/reader.cljc
- Exposes equivalent functions as the ones in `clojure.java.api.Clojure`.
- Enables the running of test.generative tests, which weren't being run.
Fixes #681
> [#681] Clojerl API

- src/erl/clj_murmur3.erl
- src/erl/lang/collections/clojerl.Set.erl
- src/erl/lang/collections/clojerl.SortedSet.erl
When there were hash collisions in the set the result of calculating its hash was wrong.
Fixes #702
> [#702] Fix hash implementation for sets

- src/erl/clj_module.erl
- src/erl/clj_utils.erl
Remove clj_module:remove/1, monitor compiling process and cleanup when it dies
Fixes #704
> [#704] Remove clj_module:remove/1, monitor compiling process and cleanup when it dies

- README.md
- scripts/Dockerfile
Hi @jfacorro ,
I've been following the project for a while now and I thought that it might help to have a docker image ready for the quickly trying out the project. I noticed that you previously did make some initiative on `docker hub` here https://hub.docker.com/r/jfacorro/clojerl but it doesn't seem to be usable.
The `Dockerfile` I've added at the moment is quite basic and so, _I've only created a draft PR asI'm looking forward to adapting the PR as to how you see fit_.
I'd really like to see `official clojerl` docker image to be there on `docker hub`.
> Add Dockerfile and publish the official Docker image

- src/erl/clj_reader.erl
- test/clj_reader_SUITE.erl
- test/clj_test_utils.hrl
There was a very subtle bug in the reader where location metadata information was always added to expressions expanded through syntax quote. The behaviour in both [`tools.reader`](https://github.com/clojure/tools.reader/blob/master/src/main/clojure/clojure/tools/reader.clj#L670) and [`clojure.lang.LispReader`](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/LispReader.java#L1122) is that metadata is only added when it includes information other than location (e.g.`:line`, `:column`, etc). 
Fixes #711.
> [#711] Stack shows wrong location for error

- scripts/profile-function
- src/erl/clj_hash_collision.erl
- src/erl/lang/clojerl.Keyword.erl
Fixes #714 
```
(simple-benchmark [coll {:foo 1 :bar 2}] (get coll :foo) 1000000)
(simple-benchmark [coll {'foo 1 'bar 2}] (get coll 'foo) 1000000)
(simple-benchmark [coll {:foo 1 :bar 2}] (:foo coll) 1000000)
(simple-benchmark [coll {'foo 1 'bar 2}] ('foo coll) 1000000)
(let [kw  :foo
sym 'foo]
(simple-benchmark [coll {:foo 1 :bar 2}] (kw coll) 1000000)
(simple-benchmark [coll {'foo 1 'bar 2}] (sym coll) 1000000))
```
```
[coll {:foo 1, :bar 2}], (get coll :foo), 1000000 runs, 148 msecs
[coll {(quote foo) 1, (quote bar) 2}], (get coll (quote foo)), 1000000 runs, 202 msecs
[coll {:foo 1, :bar 2}], (:foo coll), 1000000 runs, 172 msecs
[coll {(quote foo) 1, (quote bar) 2}], ((quote foo) coll), 1000000 runs, 213 msecs
[coll {:foo 1, :bar 2}], (kw coll), 1000000 runs, 175 msecs
[coll {(quote …
```
> [#714] Improve map get performance

- .travis.yml
- Makefile
- bin/clojerl
- bin/clojerl.bat
- rebar.config
- src/clj/clojure/core.clje
- src/clj/clojure/main.clje
- src/erl/clj_compiler.erl
- src/erl/clj_emitter.erl
- src/erl/clj_module.erl
- src/erl/clj_multimethod.erl
- src/erl/clj_reader.erl
- src/erl/clj_rt.erl
- src/erl/clojerl_cli.erl
- test/clj/clojure/test_clojure/compilation.clje
- test/clj_compiler_SUITE.erl
- Make sure that Clojerl source code can be compiled to native code using the `native` compiler option for the Erlang compiler. Because of bugs and limitation in Erlang/OTP (explained in more detailed in #310) compiling to native is only supported in Erlang/OTP 20+.
- Compiled to native code in the pipeline for the supported versions of Erlang/OTP.
- Improve the API of `clj_compiler` and the implementation of some of its functionality.
Closes #310.
> [#310] Native code compilation

- src/clj/clojure/edn.clje
- test/clj/clojure/test_clojure/edn.clje
> [#747] Set the io-reader option when calling clj_edn/read

- src/clj/clojure/core/server.clje
Fixes https://github.com/clojerl/clojerl/issues/768
Maybe we should add a testcase for this issue?
Anyway, the fix was quite simple: if the last `char` was `\n`, the line was emitted but did not include `\n` on it.
> Fixed missing \n when reading from a Socket

- src/erl/clj_reader.erl
- test/clj_reader_SUITE.erl
> [#772] Handle empty reader buffer when processing escaped chars in regex

- scripts/examples/fn.clje
- src/erl/clj_emitter.erl
> [#778] Correctly handle fn returned by macro and used as root binding for var
